### ISSUE TITLE
Create benchmarks for sending data

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#15]
### Specification

We need to create benchmarks to profile the performance of the system. These benchmarks should cover data throughput over streams. 

### Additional context

* Related #1 

### Tasks

1. Create benchmarks

**Comment by tegefaulkes** [comment]
I was writing an example benchmark for sending data. I ran into a problem running it. 

```
TypeError: Cannot read properties of undefined (reading 'isLocked')
    at QUICClient.connection (/home/faulkes/matixWorkspace/gitRepos/js-quic/node_modules/@matrixai/async-init/src/CreateDestroy.ts:151:28)
    at /home/faulkes/matixWorkspace/gitRepos/js-quic/benches/stream_1KB.ts:81:35
    at /home/faulkes/matixWorkspace/gitRepos/js-quic/node_modules/benny/lib/add.js:16:47
    at Generator.next (<anonymous>)
    at /home/faulkes/matixWorkspace/gitRepos/js-quic/node_modules/benny/lib/add.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/faulkes/matixWorkspace/gitRepos/js-quic/node_modules/benny/lib/add.js:4:12)
    at prepareCaseFn (/home/faulkes/matixWorkspace/gitRepos/js-quic/node_modules/benny/lib/add.js:15:33)
    at /home/faulkes/matixWorkspace/gitRepos/js-quic/node_modules/benny/lib/add.js:59:38
    at Generator.next (<anonymous>)

```


We've seen this before with `swc` mangling the `async-init` life-cycle decorators.

**Comment by CMCDragonkai** [comment]
I don't think we are using swc here right?

19 May 2023 17:57:45 Brian Botha ***@***.***>:

**Comment by tegefaulkes** [comment]
Yeah, I don't know much about the current set up, I'm not sure what's going on here.
